server:
  port: 8080

spring:
  sql:
    init.mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/shareit
    username: mcat
    password: 12345
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
      show_sql: true
      jdbc: time_zone=UTC
    properties:
      hibernate.format_sql: true

logging:
  level:
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: INFO
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.my: INFO
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"
