server:
  port: 8080

spring:
  sql:
    init.mode: always
    url: jdbc:h2:mem:shareit
    username: mcat
    password: Inushing1980
    driverClassName: org.h2.Driver

#  datasource:
#    url: jdbc:postgresql://localhost:5432/shareit
#    username: mcat
#    password: 12345
#    driverClassName: org.postgresql.Driver


logging:
  level:
    org.springframework.web: WARN
    org.my: INFO
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"