DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS requests;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(50) NOT NULL,
  email varchar(100) UNIQUE NOT NULL
);

CREATE TABLE  IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(50) NOT NULL,
  description varchar(100) NOT NULL,
  is_available bool NOT NULL,
  owner_id bigint NOT NULL,
  request_id bigint
);

CREATE TABLE  IF NOT EXISTS requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description varchar(200) NOT NULL,
  requester_id bigint NOT NULL,
  created timestamp(0) NOT NULL
);

CREATE TABLE  IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_date timestamp(0) NOT NULL,
  end_date timestamp(0) NOT NULL,
  item_id bigint NOT NULL,
  booker_id bigint NOT NULL,
  status varchar(15) NOT NULL
);

ALTER TABLE items ADD FOREIGN KEY (owner_id) REFERENCES users (id);

ALTER TABLE requests ADD FOREIGN KEY (requester_id) REFERENCES users (id);

ALTER TABLE bookings ADD FOREIGN KEY (item_id) REFERENCES items (id);
ALTER TABLE bookings ADD FOREIGN KEY (booker_id) REFERENCES users (id);

CREATE INDEX idx_users_id_email ON users(id,email);

CREATE INDEX idx_items_owner_id ON items(owner_id);
CREATE INDEX idx_items_id_owner_id ON items(id,owner_id);
